parameters:
#    acme_home_page.example.class: Acme\HomePageBundle\Example

services:
#    acme_home_page.example:
#        class: %acme_home_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
