acme_cash:
    resource: "@AcmeCashBundle/Controller"
    type: annotation

acme_category:
    resource: "@AcmeCategoryBundle/Controller"
    type: annotation

acme_homepage:
    resource: "@AcmeHomePageBundle/Controller"
    type: annotation

acme_user:
    resource: "@AcmeUserBundle/Controller"
    type:   annotation
    
acme_product:
    resource: "@AcmeProductBundle/Controller"
    type:   annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /auth

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
fos_user_resetting_request:
    path: /password/reset/request
    defaults: { _controller: FOSUserBundle:Resetting:request}
    
fos_user_resetting_send_email:
    path: /password/reset/send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    
fos_user_resetting_check_email:
    path: /password/reset/check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path: /password/reset
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    
fos_user_change_password:
    path: /profile/password/change
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword}
