security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: .*
            form_login:
                provider:   fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /auth/login_check
                login_path: /auth/login
            logout:
                path: /auth/logout
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product/add, role: ROLE_ADMIN }
        - { path: ^/product/edit, role: ROLE_ADMIN }
        - { path: ^/product/delete, role: ROLE_ADMIN }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/category$, role: IS_AUTHENTICATED_ANONYMOUSLY }